### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [ubco-W2020WT1-data301/course-project-group_112#3]
Hi 

- [x] Your repo is very messy please fix the folder structure. your analysis should be in the analysis folder not the data folder.

- [x] for each block of code you should explain what you did and how that helps you answer your research questions.

- [x] you should explain what your research questions are

- [x] if you have a very big plot you should remove the parts that are unnecessary or shrink it down.
having a giant plot does not actually show anything useful.

**Comment by ThatOth3rGuy** [comment]
do you want me to resubmit milestone 3 with these fixes?
